from enum import IntEnum, auto

class NonTerminal(IntEnum):
    def _generate_next_value_(name, start, count, last_values):
        start = 49
        return start + count
    
    PLINE = auto()
    P = auto()
    LDE = auto()
    DE = auto()
    T = auto()
    DT = auto()
    DC = auto()
    DF = auto()
    LP = auto()
    B = auto()
    LDV = auto()
    LS = auto()
    DV = auto()
    LI = auto()
    S = auto()
    U = auto()
    M = auto()
    E = auto()
    L = auto()
    R = auto()
    Y = auto()
    F = auto()
    LE = auto()
    LV = auto()
    IDD = auto()
    IDU = auto()
    ID = auto()
    TRUE = auto()
    FALSE = auto()
    CHR = auto()
    STR = auto()
    NUM = auto()
    NB = auto()
    MF = auto()
    MC = auto()
    NF = auto()
    MT = auto()
    ME = auto()
    MW = auto()

RuleLeftTokens = list([NonTerminal.P, NonTerminal.LDE, NonTerminal.LDE, NonTerminal.DE, NonTerminal.DE, NonTerminal.T, NonTerminal.T, NonTerminal.T, NonTerminal.T, NonTerminal.T, NonTerminal.DT, NonTerminal.DT, NonTerminal.DT, NonTerminal.DC, NonTerminal.DC, NonTerminal.DF, NonTerminal.LP, NonTerminal.LP, NonTerminal.B, NonTerminal.LDV, NonTerminal.LDV, NonTerminal.LS, NonTerminal.LS, NonTerminal.DV, NonTerminal.LI, NonTerminal.LI, NonTerminal.S, NonTerminal.S, NonTerminal.U, NonTerminal.U, NonTerminal.M, NonTerminal.M, NonTerminal.M, NonTerminal.M, NonTerminal.M, NonTerminal.M, NonTerminal.M, NonTerminal.E, NonTerminal.E, NonTerminal.E, NonTerminal.L, NonTerminal.L, NonTerminal.L, NonTerminal.L, NonTerminal.L, NonTerminal.L, NonTerminal.L, NonTerminal.R, NonTerminal.R, NonTerminal.R, NonTerminal.Y, NonTerminal.Y, NonTerminal.Y, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.F, NonTerminal.LE, NonTerminal.LE, NonTerminal.LV, NonTerminal.LV, NonTerminal.LV, NonTerminal.IDD, NonTerminal.IDU, NonTerminal.ID, NonTerminal.TRUE, NonTerminal.FALSE, NonTerminal.CHR, NonTerminal.STR, NonTerminal.NUM, NonTerminal.NB, NonTerminal.MF, NonTerminal.MC, NonTerminal.NF, NonTerminal.MT, NonTerminal.ME, NonTerminal.MW])
RuleNumberOfTokens = list([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 9, 8, 4, 5, 3, 10, 5, 3, 4, 2, 1, 2, 1, 5, 3, 1, 1, 1, 6, 9, 9, 7, 8, 2, 4, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 1, 1, 2, 2, 2, 2, 3, 5, 2, 2, 1, 1, 1, 1, 1, 3, 1, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])